spring:
  application:
    name: "newsfeed"
  datasource:
    url: "jdbc:h2:~/newsfeed/newsfeed"
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    default-encoding: UTF-8
    username: ${spring.mail.username}
    password: ${spring.mail.password}
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8081

logging:
  level:
    root: INFO
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: TRACE
#    org.springframework.security: DEBUG
#    reactor:
#      netty: DEBUG

jwt:
  secret:
    key: ${jwt.secret}
  expiry-millis: 300000 # 5?